# Generated by Django 3.1.1 on 2020-09-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200912_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_of_creation']},
        ),
    ]
